export const tweetsOfMonth = [
  "Hoje é o dia perfeito para começar algo novo e emocionante! ✨ #NovoComeço",
  "Um sorriso no rosto é a melhor maneira de enfrentar qualquer desafio. 😊 #Felicidade",
  "Lembre-se de que você é incrível e capaz de realizar grandes coisas. 💪 #Autoconfiança",
  "Aproveite o dia para fazer algo gentil por alguém. Pequenos gestos fazem a diferença. 🤗 #Bondade",
  "A imaginação é o limite. O que você vai criar hoje? 🌟 #Criatividade",
  "A vida é cheia de surpresas maravilhosas. Esteja aberto para recebê-las. 🎁 #Surpresas",
  "Não tenha medo de falhar; veja isso como uma oportunidade de aprender e crescer. 📈 #Crescimento",
  "A gratidão transforma o que temos em suficiente. 🙏 #Gratidão",
  "Seja a mudança que você deseja ver no mundo. 👏 #Mudança",
  "Lembre-se de cuidar de si mesmo hoje. Sua saúde mental é importante. ❤️ #AutoCuidado",
  "Sua jornada é única e especial. Aproveite cada passo dela. 🌈 #Jornada",
  "A simplicidade é a chave para a verdadeira sofisticação. 🌼 #Simplicidade",
  "Compartilhe um elogio com alguém hoje. Elogios elevam o espírito. 💬 #Elogio",
  "O sucesso começa com a decisão de tentar. 💼 #Sucesso",
  "Inspire-se pela beleza ao seu redor. 🌸 #Inspiração",
  "Hoje é o dia perfeito para perseguir seus sonhos com paixão. 🚀 #Paixão",
  "Aprenda algo novo todos os dias; o conhecimento é poder. 📚 #Aprendizado",
  "A vida é uma aventura ousada ou nada. 🌏 #Aventura",
  "Mantenha a calma e continue seguindo em frente. 🚶 #Persistência",
  "Você é mais forte do que pensa. 💪 #ForçaInterior",
  "Cultive relacionamentos genuínos; são tesouros na vida. 👫 #Amizade",
  "Aproveite cada momento, pois eles não voltam. ⏳ #Aproveite",
  "Não adie o que pode ser feito hoje. 📅 #Proatividade",
  "Celebre suas realizações, não importa o quão pequenas pareçam. 🎉 #Celebração",
  "Seja a luz no mundo de alguém hoje. 💡 #Bondade",
  "A vida é uma jornada, não um destino. 🌄 #Jornada",
  "Confie no processo da vida e siga em frente com fé. 🙌 #Fé",
  "O que você pode fazer hoje para tornar o mundo um lugar melhor? 🌍 #MudançaPositiva",
  "Nunca desista dos seus sonhos; eles são a essência da vida. ✨ #Sonhos"
]